name: Deploy Nexus OSS via Docker to AWS VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Docker and deploy Nexus OSS on AWS VM
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_KEY }}
          port: 22
          script: |
            set -euo pipefail

            # Update and install Docker if missing
            sudo apt-get update -y
            sudo apt-get install -y docker.io curl

            # Start and enable Docker
            sudo systemctl start docker
            sudo systemctl enable docker

            # Stop and remove old Nexus container if it exists
            sudo docker stop nexus || true
            sudo docker rm nexus || true

            # Create persistent data dir
            sudo mkdir -p /opt/nexus-data
            sudo chown -R 200:200 /opt/nexus-data

            # Pull latest Nexus OSS image
            sudo docker pull sonatype/nexus3:latest

            # Run Nexus container
            sudo docker run -d --name nexus \
              -p 8081:8081 \
              -v /opt/nexus-data:/nexus-data \
              sonatype/nexus3:latest

            # Allow Nexus port in firewall (if UFW is used)
            sudo ufw allow 8081/tcp || true
            sudo ufw reload || true

            # Wait for Nexus to initialize a bit
            echo "Waiting 30s for Nexus to write admin password..."
            sleep 30

            # Print Nexus container status
            sudo docker ps -a

            # Show initial admin password (first-time setup)
            if sudo docker exec nexus test -f /nexus-data/admin.password; then
              echo "============================"
              echo "Initial Nexus admin password:"
              sudo docker exec nexus cat /nexus-data/admin.password
              echo "============================"
            else
              echo "Admin password file not found yet. Try again in 1-2 minutes."
            fi
