name: Deploy Nexus to AWS VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nexus on AWS VM
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_KEY }}
          port: 22
          script: |
            sudo apt update -y
            sudo apt install -y wget openjdk-8-jre-headless
            wget https://download.sonatype.com/nexus/3/nexus-3.59.0-02-unix.tar.gz
            tar -xvf nexus-3.59.0-02-unix.tar.gz
            sudo mv nexus-3.59.0-02 /opt/nexus
            sudo useradd -r -m -d /opt/nexus nexus
            sudo chown -R nexus:nexus /opt/nexus
            sudo -u nexus /opt/nexus/bin/nexus start
            sudo ufw allow 8081/tcp
            sudo ufw reload
